export { default as ContactHero} from "./contact/ContactHero";
export { default as ContactDetails} from "./contact/ContactDetails";
export { default as ContactForm} from "./contact/ContactForm";
export { default as FeaturedProduct } from "./FeaturedProduct";
export {default as TodayDeals} from "./TodayDeals";
export { default as Benefits } from "./Benefits";
export {default as Categories} from "./Categories";
export {default as Logo} from "./Logo";
export {default as  Hero} from "./Hero";
export {default as Footer} from "./Footer";
export {default as Navbar} from "./Navbar";
export {default as Testimonials} from "./Testimonials";