export { default as ContactHero} from "./contact/ContactHero";
export { default as ContactDetails} from "./contact/ContactDetails";
export { default as ContactForm} from "./contact/ContactForm";
export { default as FeaturedProduct } from "./home/FeaturedProduct";
export {default as TodayDeals} from "./home/TodayDeals";
export { default as Benefits } from "./home/Benefits";
export {default as Categories} from "./home/Categories";
export {default as Logo} from "./Logo";
export {default as  Hero} from "./home/Hero";
export {default as Footer} from "./Footer";
export {default as Navbar} from "./Navbar";
export {default as Testimonials} from "./Testimonials";
export {default as ProductDescriptionI} from "./ProductDescriptionI";
export {default as ProductDescriptionII} from "./ProductDescriptionII";
export {default as ProductDescriptionIII} from "./ProductDescriptionIII";
export {default as ProductDescriptionIV} from "./ProductDescriptionIV";
export {default as ProductDescriptionV} from "./ProductDescriptionV";
export {default as ProductDescriptionVI} from "./ProductDescriptionVI";
export {default as ProductDescriptionVII} from "./ProductDescriptionVII";
export {default as ProductDescriptionVIII} from "./ProductDescriptionVIII";
export { default as Adminsidemenu } from "./admincomp/Adminsidemenu";